# VISUALIZATIONS

Output of each function are paramters that can be used in Apache ECharts

In [47]:
import pandas as pd

## Waterfall Plot

In [48]:
def waterfall_plot(df: pd.DataFrame, x: str, y: str, title: str):
    vals = df[y].to_list()
    color_labels =[]
    for i in range (1, len(vals)):
        if vals[i] > vals[i-1]:
            color_labels.append('i')
            i_list = [vals[0]]
            d_list = ['-']
        else:
            color_labels.append('d')
            i_list = ['-']
            d_list = [0]
    y = [0]
    c = 0
    for i in range(1, len(vals)):
        if color_labels[c] == 'd':
            y.append(round(vals[i], 2))
            d_list.append(round(vals[i-1] - vals[i], 2))
            i_list.append('-')
        else:
            y.append(vals[i-1])
            i_list.append(round(vals[i] - vals[i-1], 2))
            d_list.append('-')
        c += 1
    return {
        't': title,
        'x': df[x].to_list(),
        'y': y,
        'i': i_list,
        'd': d_list
    }

In [49]:
df = pd.read_csv('data/2/Electric_Production.csv')
df['Year'] = df['DATE'].apply(lambda x: x[-4:])
df.head()

       DATE  IPG2211A2N  Year
0  1/1/1985     72.5052  1985
1  2/1/1985     70.6720  1985
2  3/1/1985     62.4502  1985
3  4/1/1985     57.4714  1985
4  5/1/1985     55.3151  1985

In [50]:
df = pd.DataFrame(df[df['Year'] == '1985'])
df

         DATE  IPG2211A2N  Year
0    1/1/1985     72.5052  1985
1    2/1/1985     70.6720  1985
2    3/1/1985     62.4502  1985
3    4/1/1985     57.4714  1985
4    5/1/1985     55.3151  1985
5    6/1/1985     58.0904  1985
6    7/1/1985     62.6202  1985
7    8/1/1985     63.2485  1985
8    9/1/1985     60.5846  1985
9   10/1/1985     56.3154  1985
10  11/1/1985     58.0005  1985
11  12/1/1985     68.7145  1985

In [51]:
waterfall_plot(df, 'DATE', 'IPG2211A2N', 'Electric Production')

{'t': 'Electric Production',
 'x': ['1/1/1985',
  '2/1/1985',
  '3/1/1985',
  '4/1/1985',
  '5/1/1985',
  '6/1/1985',
  '7/1/1985',
  '8/1/1985',
  '9/1/1985',
  '10/1/1985',
  '11/1/1985',
  '12/1/1985'],
 'y': [0,
  70.67,
  62.45,
  57.47,
  55.32,
  55.3151,
  58.0904,
  62.6202,
  60.58,
  56.32,
  56.3154,
  58.0005],
 'i': [72.5052, '-', '-', '-', '-', 2.78, 4.53, 0.63, '-', '-', 1.69, 10.71],
 'd': ['-', 1.83, 8.22, 4.98, 2.16, '-', '-', '-', 2.66, 4.27, '-', '-']}

## Stacked Area Plot

In [52]:
def stacked_area_plot(df, columns, x, title):
    return {
        'title': title,
        'names': columns,
        'vals': list(df[columns].values.T),
        'x': df[x].to_list()
    }

In [53]:
df = pd.read_csv('data/3/DailyDelhiClimateTrain.csv')
df

            date   meantemp    humidity  wind_speed  meanpressure
0     2013-01-01  10.000000   84.500000    0.000000   1015.666667
1     2013-01-02   7.400000   92.000000    2.980000   1017.800000
2     2013-01-03   7.166667   87.000000    4.633333   1018.666667
3     2013-01-04   8.666667   71.333333    1.233333   1017.166667
4     2013-01-05   6.000000   86.833333    3.700000   1016.500000
...          ...        ...         ...         ...           ...
1457  2016-12-28  17.217391   68.043478    3.547826   1015.565217
1458  2016-12-29  15.238095   87.857143    6.000000   1016.904762
1459  2016-12-30  14.095238   89.666667    6.266667   1017.904762
1460  2016-12-31  15.052632   87.000000    7.325000   1016.100000
1461  2017-01-01  10.000000  100.000000    0.000000   1016.000000

[1462 rows x 5 columns]

In [54]:
x = stacked_area_plot(df, ['meantemp', 'humidity', 'wind_speed', 'meanpressure'], 'date', 'Delhi weather')

In [55]:
x['x'][:30]

['2013-01-01',
 '2013-01-02',
 '2013-01-03',
 '2013-01-04',
 '2013-01-05',
 '2013-01-06',
 '2013-01-07',
 '2013-01-08',
 '2013-01-09',
 '2013-01-10',
 '2013-01-11',
 '2013-01-12',
 '2013-01-13',
 '2013-01-14',
 '2013-01-15',
 '2013-01-16',
 '2013-01-17',
 '2013-01-18',
 '2013-01-19',
 '2013-01-20',
 '2013-01-21',
 '2013-01-22',
 '2013-01-23',
 '2013-01-24',
 '2013-01-25',
 '2013-01-26',
 '2013-01-27',
 '2013-01-28',
 '2013-01-29',
 '2013-01-30']

In [56]:
[round(i/10, 3) for i in x['vals'][3][:30].tolist()], x['names'][3]

([101.567,
  101.78,
  101.867,
  101.717,
  101.65,
  101.8,
  102.0,
  101.871,
  101.7,
  101.567,
  101.614,
  101.557,
  101.333,
  101.517,
  101.586,
  101.667,
  101.583,
  101.45,
  102.167,
  102.029,
  102.1,
  102.18,
  102.05,
  102.05,
  102.075,
  101.967,
  101.814,
  101.783,
  101.662,
  101.786],
 'meanpressure')

In [57]:
x['names']

['meantemp', 'humidity', 'wind_speed', 'meanpressure']

In [58]:
x['title']

'Delhi weather'

## Lag Plot

In [59]:
from sklearn.cluster import KMeans

In [60]:
def lag_plot(timeseries, lag, data_reduce = 1):
    x = timeseries.values[:-lag].tolist()
    y = timeseries.values[lag:].tolist()
    data = []
    for i in range(len(x)):
        data.append([x[i], y[i]])
    kmeans = KMeans(int(len(data)/data_reduce))
    kmeans.fit(data)
    data = kmeans.cluster_centers_
    return data.tolist()

In [61]:
lag_plot(df['meantemp'], 3, 10)

/home/shail/miniconda3/lib/python3.10/site-packages/sklearn/cluster/_kmeans.py:870: FutureWarning: The default value of `n_init` will change from 10 to 'auto' in 1.4. Set the value of `n_init` explicitly to suppress the warning
  warnings.warn(

[[35.85739926739927, 31.507453007518798],
 [21.04269086176981, 22.8656008465219],
 [13.624509803921567, 12.196183473389356],
 [27.366769547325102, 30.296835839598998],
 [31.385592592592594, 33.822698412698415],
 [18.405238095238097, 18.424999999999997],
 [33.03386752136752, 30.77001322751323],
 [25.95625, 25.88690476190476],
 [34.51315359477124, 35.15310846560846],
 [15.00595238095238, 16.39330357142857],
 [31.763917795167796, 29.68836113233172],
 [30.00934065934066, 32.34134615384615],
 [24.93945868945869, 26.01674603174603],
 [23.467853481261784, 21.490079365079364],
 [6.5, 9.928571428571429],
 [18.09027777777778, 15.6984126984127],
 [12.616156462585037, 14.853103741496598],
 [37.41334033613445, 37.59142857142857],
 [27.717559523809523, 27.35054945054945],
 [31.175925925925924, 26.687698412698413],
 [11.504978354978356, 12.30681818181818],
 [29.67939484126984, 30.607334799861974],
 [31.229108470032383, 32.25285348139515],
 [28.412306148513046, 29.3787107209521],
 [32.618021616541355, 37.24242424242424],
 [35.375, 27.716666666666665],
 [28.04642857142857, 23.123809523809523],
 [15.763690476190476, 17.9334478021978],
 [19.69560982495765, 21.03841991341991],
 [17.32504400361543, 19.96526360544218],
 [18.62777777777778, 13.037500000000001],
 [25.15654761904762, 30.65561224489796],
 [21.486944444444443, 18.52051282051282],
 [22.730249903605166, 23.69389063317635],
 [28.64664502164502, 32.68948412698413],
 [15.141794217687075, 13.943452380952381],
 [9.53125, 9.197916666666668],
 [37.79549319727891, 34.81853741496599],
 [21.24702380952381, 24.992063492063494],
 [32.011160714285715, 35.2267342032967],
 [34.37361111111111, 33.78935185185185],
 [12.138020833333334, 16.94142316017316],
 [24.037450396825395, 27.593204365079366],
 [30.655116886001444, 30.77136625826281],
 [18.38214285714286, 23.333104395604394],
 [17.54883658008658, 16.68574735449735],
 [34.31785714285714, 29.724867724867725],
 [25.21110119047619, 22.57667824074074],
 [11.229166666666666, 15.055555555555557],
 [20.09722222222222, 16.959656084656086],
 [30.713541666666668, 28.81294642857143],
 [26.848544973544975, 25.064764492753625],
 [17.186507936507937, 13.42361111111111],
 [33.36770833333333, 27.863508597883598],
 [29.529571123321123, 27.453189300411523],
 [26.8125, 37.5625],
 [35.87654761904762, 35.73047619047619],
 [27.20261904761905, 31.666503139717424],
 [9.25, 12.3125],
 [11.864642857142858, 13.52797619047619],
 [18.117494493810284, 17.347385509227614],
 [21.272161172161173, 20.192857142857143],
 [35.633273809523814, 33.07053571428571],
 [11.895833333333332, 9.866071428571427],
 [14.4609375, 14.753348214285714],
 [30.326190476190476, 35.207131185807654],
 [29.775, 25.786666666666665],
 [7.744444444444447, 6.666666666666668],
 [36.17321428571429, 38.08469387755102],
 [14.829166666666666, 18.97797619047619],
 [23.223484848484848, 19.60326086956522],
 [33.27889739229025, 32.99092887154862],
 [18.049107142857142, 21.328125],
 [25.210069444444443, 24.70282634032634],
 [33.02916666666667, 34.237896825396824],
 [25.475, 28.57142857142857],
 [22.50426173941799, 22.78027626811594],
 [33.002959753345785, 31.5325],
 [37.625, 30.45],
 [16.50408163265306, 14.462585034013607],
 [13.09733893557423, 13.133333333333333],
 [21.780416666666667, 21.906481950067477],
 [29.286472922502334, 31.700892857142858],
 [28.632174422799423, 28.419575216450216],
 [32.18055555555556, 30.71362433862434],
 [28.172916666666666, 34.63229166666667],
 [26.513392857142858, 21.09375],
 [10.125000000000002, 10.946428571428571],
 [26.5, 33.625],
 [38.27272727272727, 26.8125],
 [24.44088319088319, 24.922876249265137],
 [19.711174242424242, 18.50071548821549],
 [15.121825396825397, 12.291666666666668],
 [26.012889476778366, 24.666412291412293],
 [17.125517598343684, 15.048454469507101],
 [34.61547619047619, 36.96774509803922],
 [14.408482142857142, 15.773809523809524],
 [23.391118266797616, 24.095051742919388],
 [15.902380952380952, 20.166666666666668],
 [17.15074404761905, 18.207142857142856],
 [21.333333333333336, 16.5],
 [34.306448412698415, 31.08779761904762],
 [32.06441064079953, 28.482208994708994],
 [12.472470238095237, 11.593105158730157],
 [18.835834037757117, 19.589160839160837],
 [30.063868220899472, 28.24828869047619],
 [23.710595238095237, 25.680833333333332],
 [30.929464285714285, 36.36458333333333],
 [19.41200396825397, 15.706501831501832],
 [27.7333547008547, 26.17853835978836],
 [30.90566488685482, 29.91285369220152],
 [35.9141156462585, 34.205527210884355],
 [19.875, 25.375],
 [7.0, 14.0],
 [37.260714285714286, 32.63309671694765],
 [31.33970183150183, 31.079422832722834],
 [25.0, 18.25],
 [24.7094893589847, 23.774571823678965],
 [37.74821428571428, 36.16642857142857],
 [30.219812925170068, 33.20191798941799],
 [23.70229091421399, 22.88380132687825],
 [29.42116251803752, 29.509774831649832],
 [28.475, 30.802857142857142],
 [28.71734693877551, 24.800680272108842],
 [14.257440476190474, 10.125],
 [26.248129251700682, 29.712585034013607],
 [32.706944444444446, 29.806893004115224],
 [33.251658305462655, 35.69368131868132],
 [26.396428571428572, 27.025833333333335],
 [34.22727272727273, 32.01758658008658],
 [16.958333333333336, 11.595238095238097],
 [27.268018812463257, 28.52791005291005],
 [16.914081289081288, 15.753174603174605],
 [30.32181389463998, 31.61305725010829],
 [15.737445887445888, 15.490530303030303],
 [32.01054167668751, 31.90732959555876],
 [19.14755291005291, 17.679761904761904],
 [22.65416666666667, 25.214583333333334],
 [8.857142857142858, 15.714285714285714],
 [35.56865079365079, 30.299107142857142],
 [16.3702876984127, 19.02857142857143],
 [32.14477318977319, 32.98239627142405],
 [13.933333333333334, 17.136335403726704],
 [15.865638207945901, 16.97394272394272],
 [27.326785714285716, 23.938095238095237]]