# Dataset: [Daily Delhi Climate](https://www.kaggle.com/datasets/sumanthvrao/daily-climate-time-series-data)

In [48]:
import pandas as pd

In [49]:
df = pd.read_csv('../../datasets/3/DailyDelhiClimateTrain.csv')

In [50]:
df

            date   meantemp    humidity  wind_speed  meanpressure
0     2013-01-01  10.000000   84.500000    0.000000   1015.666667
1     2013-01-02   7.400000   92.000000    2.980000   1017.800000
2     2013-01-03   7.166667   87.000000    4.633333   1018.666667
3     2013-01-04   8.666667   71.333333    1.233333   1017.166667
4     2013-01-05   6.000000   86.833333    3.700000   1016.500000
...          ...        ...         ...         ...           ...
1457  2016-12-28  17.217391   68.043478    3.547826   1015.565217
1458  2016-12-29  15.238095   87.857143    6.000000   1016.904762
1459  2016-12-30  14.095238   89.666667    6.266667   1017.904762
1460  2016-12-31  15.052632   87.000000    7.325000   1016.100000
1461  2017-01-01  10.000000  100.000000    0.000000   1016.000000

[1462 rows x 5 columns]

In [51]:
df.isna().sum()

date            0
meantemp        0
humidity        0
wind_speed      0
meanpressure    0
dtype: int64

In [52]:
import sys
sys.path.insert(0, '/home/shail/bits/PS1/time_series_analysis')

original_stdout = sys.stdout 
	
def outfile(x):
    with open('output.txt', 'w') as f:
        sys.stdout = f
        print(x)
        sys.stdout = original_stdout

In [53]:
from tsa.dateconverter import DateConverter

### Filtering

In [54]:
df['Year'] = df['date'].apply(lambda x: x[:4])
df = pd.DataFrame(df[df['Year'] == '2016'])
df.drop(['Year'], axis = 1, inplace = True)
df

            date   meantemp   humidity  wind_speed  meanpressure
1095  2016-01-01  14.714286  72.285714    1.057143   1021.142857
1096  2016-01-02  14.000000  75.875000    2.087500   1021.000000
1097  2016-01-03  14.375000  74.750000    5.112500   1018.500000
1098  2016-01-04  15.750000  77.125000    0.000000   1017.625000
1099  2016-01-05  15.833333  88.833333    0.616667   1017.000000
...          ...        ...        ...         ...           ...
1456  2016-12-27  16.850000  67.550000    8.335000   1017.200000
1457  2016-12-28  17.217391  68.043478    3.547826   1015.565217
1458  2016-12-29  15.238095  87.857143    6.000000   1016.904762
1459  2016-12-30  14.095238  89.666667    6.266667   1017.904762
1460  2016-12-31  15.052632  87.000000    7.325000   1016.100000

[366 rows x 5 columns]

# Date Conversion

In [55]:
converter = DateConverter()
df['date'] = df['date'].apply(lambda x: converter.convert_date(x, infer_format=True))
df

           date   meantemp   humidity  wind_speed  meanpressure
1095 2016-01-01  14.714286  72.285714    1.057143   1021.142857
1096 2016-01-02  14.000000  75.875000    2.087500   1021.000000
1097 2016-01-03  14.375000  74.750000    5.112500   1018.500000
1098 2016-01-04  15.750000  77.125000    0.000000   1017.625000
1099 2016-01-05  15.833333  88.833333    0.616667   1017.000000
...         ...        ...        ...         ...           ...
1456 2016-12-27  16.850000  67.550000    8.335000   1017.200000
1457 2016-12-28  17.217391  68.043478    3.547826   1015.565217
1458 2016-12-29  15.238095  87.857143    6.000000   1016.904762
1459 2016-12-30  14.095238  89.666667    6.266667   1017.904762
1460 2016-12-31  15.052632  87.000000    7.325000   1016.100000

[366 rows x 5 columns]

# Visualizations

In [56]:
from tsa.visualization import *

In [57]:
small_df = pd.DataFrame(df[:15])
small_df

           date   meantemp   humidity  wind_speed  meanpressure
1095 2016-01-01  14.714286  72.285714    1.057143   1021.142857
1096 2016-01-02  14.000000  75.875000    2.087500   1021.000000
1097 2016-01-03  14.375000  74.750000    5.112500   1018.500000
1098 2016-01-04  15.750000  77.125000    0.000000   1017.625000
1099 2016-01-05  15.833333  88.833333    0.616667   1017.000000
1100 2016-01-06  17.375000  81.625000    2.312500   1016.500000
1101 2016-01-07  17.125000  87.000000    0.000000   1018.125000
1102 2016-01-08  15.500000  83.250000    7.887500   1017.250000
1103 2016-01-09  15.857143  65.142857    8.471429   1015.428571
1104 2016-01-10  15.625000  74.375000    2.775000   1017.500000
1105 2016-01-11  15.750000  74.875000    1.625000   1017.500000
1106 2016-01-12  18.000000  69.687500    6.031250   1014.937500
1107 2016-01-13  18.266667  75.800000    5.080000   1014.333333
1108 2016-01-14  15.562500  80.437500    4.300000   1016.125000
1109 2016-01-15  13.000000  84.187500   10.775000   1017.000000

## Waterfall Plot

In [58]:
plot_params = waterfall_plot(small_df, 'date', 'meantemp', 'Waterfall plot of Weather', remove_time=True)

In [59]:
outfile(plot_params['x'])

## Lag Plot

In [60]:
data = lag_plot(df['humidity'], 50, 'Lag plot of electric production', 1)

/home/shail/bits/PS1/time_series_analysis/env/lib/python3.10/site-packages/sklearn/cluster/_kmeans.py:870: FutureWarning: The default value of `n_init` will change from 10 to 'auto' in 1.4. Set the value of `n_init` explicitly to suppress the warning
  warnings.warn(

In [61]:
outfile(data['data'])

## Stacked Area Chart

In [62]:
stacked_area_plot(df, ['meantemp', 'humidity', 'wind_speed'], 'date', 'stacked_area_plot')

{'title': 'stacked_area_plot',
 'names': ['meantemp', 'humidity', 'wind_speed'],
 'vals': [[14.714285714285714,
   14.0,
   14.375,
   15.75,
   15.833333333333334,
   17.375,
   17.125,
   15.5,
   15.857142857142858,
   15.625,
   15.75,
   18.0,
   18.266666666666666,
   15.5625,
   13.0,
   13.6,
   14.0,
   13.266666666666667,
   12.357142857142858,
   12.066666666666666,
   12.1875,
   11.733333333333333,
   14.4375,
   11.1875,
   11.666666666666666,
   14.5625,
   17.583333333333332,
   16.857142857142858,
   19.5625,
   20.142857142857142,
   17.375,
   15.846153846153848,
   15.266666666666667,
   13.125,
   16.363636363636363,
   12.666666666666666,
   15.333333333333334,
   15.625,
   17.09090909090909,
   17.76923076923077,
   18.133333333333333,
   19.6875,
   19.2,
   17.066666666666666,
   17.642857142857142,
   17.6,
   18.214285714285715,
   18.714285714285715,
   19.466666666666665,
   23.153846153846157,
   23.625,
   21.0,
   21.0,
   21.428571428571427,
   21.6875,
   22.5625,
   22.8,
   22.8,
   23.0,
   23.875,
   24.916666666666668,
   24.933333333333334,
   26.0,
   27.3125,
   23.933333333333334,
   22.8125,
   23.714285714285715,
   23.428571428571427,
   24.0,
   25.5625,
   25.066666666666663,
   24.5625,
   24.25,
   22.375,
   24.066666666666663,
   23.9375,
   26.3125,
   26.1875,
   26.785714285714285,
   27.133333333333333,
   26.625,
   25.0625,
   26.2,
   28.133333333333333,
   29.875,
   24.666666666666668,
   26.25,
   25.933333333333334,
   27.125,
   29.571428571428573,
   30.0,
   30.571428571428573,
   32.3125,
   33.3125,
   32.8125,
   32.3125,
   31.375,
   29.933333333333334,
   29.266666666666666,
   30.73333333333333,
   32.25,
   29.8,
   30.2,
   31.75,
   33.125,
   33.625,
   35.6875,
   34.666666666666664,
   34.625,
   34.0,
   34.0625,
   34.0,
   33.25,
   31.916666666666668,
   31.3125,
   31.75,
   33.4375,
   33.125,
   34.15384615384615,
   34.07142857142857,
   33.0625,
   34.6875,
   38.0,
   35.5,
   33.714285714285715,
   30.6,
   31.4375,
   33.3125,
   35.13333333333333,
   33.53333333333333,
   34.0,
   32.5,
   35.375,
   37.294117647058826,
   36.5625,
   37.25,
   37.21428571428572,
   37.5,
   37.75,
   37.375,
   37.4,
   36.13333333333333,
   36.8,
   32.214285714285715,
   31.526315789473685,
   33.21739130434783,
   35.26923076923077,
   38.27272727272727,
   36.0625,
   31.5,
   26.8125,
   32.642857142857146,
   36.0,
   37.5625,
   37.5625,
   38.2,
   36.16666666666666,
   35.42857142857143,
   34.625,
   36.07142857142857,
   35.733333333333334,
   36.13333333333333,
   33.4375,
   35.5,
   36.0,
   32.625,
   34.733333333333334,
   33.5,
   34.1875,
   35.857142857142854,
   35.625,
   30.9375,
   32.875,
   33.125,
   33.84615384615385,
   36.4375,
   35.42857142857143,
   34.86666666666667,
   34.3125,
   30.785714285714285,
   35.375,
   35.46666666666667,
   32.125,
   28.4,
   29.5625,
   30.6875,
   33.25,
   33.266666666666666,
   33.5,
   30.8,
   33.25,
   32.5625,
   31.5,
   30.5,
   31.25,
   30.4375,
   31.0,
   27.125,
   28.125,
   27.666666666666668,
   32.3125,
   34.1875,
   34.13333333333333,
   34.125,
   31.875,
   31.4375,
   31.9375,
   30.3125,
   28.3125,
   29.53333333333333,
   27.375,
   27.33333333333333,
   29.266666666666666,
   29.125,
   30.6875,
   32.5625,
   33.111111111111114,
   33.8,
   30.066666666666663,
   33.11764705882353,
   33.80952380952381,
   31.615384615384617,
   32.0,
   28.107142857142858,
   29.035714285714285,
   30.321428571428573,
   28.933333333333334,
   31.678571428571427,
   31.33333333333333,
   29.928571428571427,
   29.88888888888889,
   32.07142857142857,
   33.18518518518518,
   31.59259259259259,
   32.18518518518518,
   31.48,
   30.178571428571427,
   31.52,
   31.22222222222222,
   31.785714285714285,
   33.4,
   29.571428571428573,
   30.04,
   27.25925925925926,
   27.96,
   30.73913043478261,
   30.894736842105264,
   31.692307692307693,
   31.07692307692308,
   30.375,
   31.1,
   31.916666666666668,
   30.55555555555556,
   31.23076923076923,
   31.0,
   31.642857142857142,
   32.53333333333333,
   30.857142857142858,
   31.727272727272727,
   31.4,
   32.30769230769231,
   32.25,
   32.375,
   33.44444444444444,
   33.36,
   30.03703703703704,
   31.0,
   31.24,
   31.130434782608692,
   31.48,
   32.18518518518518,
   32.44,
   32.22727272727273,
   32.214285714285715,
   32.541666666666664,
   32.81481481481482,
   33.26923076923077,
   30.55555555555556,
   28.83333333333333,
   30.703703703703702,
   30.96,
   30.6,
   30.92,
   29.77777777777778,
   29.666666666666668,
   29.571428571428573,
   29.96296296296296,
   29.75,
   27.74074074074074,
   28.428571428571427,
   28.6,
   28.5,
   28.925925925925927,
   29.07692307692308,
   28.40909090909091,
   29.33333333333333,
   27.5,
   28.5,
   28.04,
   27.57692307692308,
   26.55555555555556,
   25.51851851851852,
   25.814814814814813,
   24.82608695652174,
   24.53846153846154,
   24.384615384615383,
   23.727272727272727,
   25.64,
   24.814814814814813,
   23.115384615384617,
   22.925925925925927,
   24.545454545454547,
   23.73076923076923,
   23.0,
   23.51851851851852,
   23.92,
   23.53846153846154,
   24.296296296296298,
   23.346153846153847,
   22.24,
   21.76923076923077,
   21.73076923076923,
   21.73076923076923,
   20.666666666666668,
   22.25,
   21.53846153846154,
   22.57894736842105,
   22.82608695652174,
   21.42105263157895,
   23.6,
   24.294117647058822,
   23.63636363636364,
   22.454545454545453,
   21.61111111111111,
   19.869565217391305,
   19.75,
   19.20833333333333,
   21.20833333333333,
   18.9,
   18.63636363636364,
   18.53846153846154,
   18.25,
   16.9,
   19.416666666666668,
   16.444444444444443,
   20.041666666666668,
   19.90909090909091,
   19.05,
   18.55555555555556,
   18.166666666666668,
   15.833333333333334,
   17.5,
   16.083333333333332,
   17.857142857142858,
   19.8,
   18.05,
   17.285714285714285,
   15.55,
   17.318181818181817,
   14.0,
   17.142857142857142,
   16.85,
   17.217391304347824,
   15.238095238095235,
   14.095238095238097,
   15.052631578947368],
  [72.28571428571429,
   75.875,
   74.75,
   77.125,
   88.83333333333333,
   81.625,
   87.0,
   83.25,
   65.14285714285714,
   74.375,
   74.875,
   69.6875,
   75.8,
   80.4375,
   84.1875,
   80.06666666666666,
   77.66666666666667,
   80.46666666666667,
   88.57142857142857,
   84.2,
   73.1875,
   83.4,
   75.875,
   86.25,
   75.4,
   79.6875,
   69.16666666666667,
   69.35714285714286,
   70.625,
   78.5,
   78.25,
   65.76923076923077,
   55.86666666666667,
   66.5,
   53.0,
   70.66666666666667,
   69.5,
   77.0,
   67.18181818181819,
   67.46153846153847,
   64.86666666666666,
   54.75,
   57.86666666666667,
   62.13333333333333,
   61.92857142857143,
   59.53333333333333,
   56.142857142857146,
   59.285714285714285,
   76.0,
   70.23076923076923,
   73.125,
   61.125,
   51.42857142857143,
   50.642857142857146,
   58.0625,
   57.5,
   55.6,
   59.0,
   63.0625,
   63.9375,
   57.41666666666666,
   57.06666666666667,
   55.61538461538461,
   44.25,
   57.13333333333333,
   66.5625,
   64.14285714285714,
   60.21428571428572,
   57.5625,
   57.4375,
   67.8,
   66.9375,
   65.1875,
   66.0,
   58.93333333333333,
   53.75,
   50.3125,
   61.25,
   61.85714285714285,
   58.73333333333333,
   43.375,
   37.875,
   43.266666666666666,
   46.86666666666667,
   50.1875,
   62.66666666666666,
   53.6875,
   52.8,
   47.75,
   39.785714285714285,
   39.73333333333333,
   38.21428571428572,
   38.5625,
   44.25,
   33.125,
   29.3125,
   33.125,
   37.0,
   36.0,
   32.46666666666667,
   29.0,
   35.0,
   36.2,
   28.0625,
   23.875,
   25.375,
   23.6875,
   23.866666666666667,
   30.125,
   33.6,
   25.9375,
   24.666666666666668,
   24.25,
   21.818181818181817,
   22.125,
   22.8125,
   25.1875,
   29.0625,
   21.76923076923077,
   23.285714285714285,
   25.5625,
   23.375,
   18.466666666666665,
   30.375,
   31.857142857142858,
   42.0,
   37.4375,
   37.1875,
   36.333333333333336,
   40.6,
   39.75,
   49.9375,
   40.0,
   28.11764705882353,
   31.875,
   29.5,
   23.5,
   25.8125,
   27.625,
   40.5,
   44.2,
   45.4,
   44.8,
   47.92857142857143,
   53.526315789473685,
   46.60869565217392,
   44.57692307692308,
   26.09090909090909,
   37.25,
   57.0625,
   74.8125,
   51.21428571428572,
   42.2,
   35.3125,
   40.6875,
   42.06666666666667,
   51.75,
   45.71428571428572,
   59.1875,
   44.642857142857146,
   43.73333333333333,
   41.86666666666667,
   49.9375,
   37.125,
   43.3125,
   55.125,
   48.86666666666667,
   51.285714285714285,
   52.25,
   50.57142857142857,
   53.25,
   73.9375,
   62.1875,
   60.8125,
   51.61538461538461,
   46.5625,
   55.92857142857143,
   57.46666666666667,
   61.25,
   75.07142857142857,
   58.875,
   60.2,
   73.4,
   80.0,
   78.125,
   76.3125,
   68.6875,
   64.06666666666666,
   63.0,
   75.86666666666666,
   66.0625,
   65.6875,
   71.9375,
   80.1875,
   76.3125,
   80.4375,
   78.0625,
   93.875,
   86.5625,
   91.26666666666668,
   69.125,
   59.5625,
   56.86666666666667,
   56.125,
   66.0,
   72.25,
   69.125,
   82.0,
   88.25,
   81.33333333333333,
   92.4375,
   92.26666666666668,
   83.13333333333334,
   84.25,
   72.125,
   63.5625,
   63.888888888888886,
   61.66666666666666,
   76.0,
   65.17647058823529,
   62.38095238095238,
   71.65384615384616,
   71.25925925925925,
   89.46428571428571,
   85.0,
   77.07142857142857,
   83.7,
   67.64285714285714,
   66.41666666666667,
   72.5,
   79.81481481481481,
   68.28571428571429,
   66.48148148148148,
   68.07407407407408,
   65.55555555555556,
   70.08,
   79.28571428571429,
   72.44,
   73.81481481481481,
   70.28571428571429,
   66.24,
   82.32142857142857,
   76.8,
   89.55555555555556,
   87.24,
   71.73913043478261,
   62.68421052631579,
   59.30769230769231,
   60.30769230769231,
   55.0,
   57.7,
   58.0,
   56.66666666666666,
   58.23076923076923,
   56.4,
   55.5,
   57.06666666666667,
   70.35714285714286,
   59.63636363636363,
   58.0,
   58.0,
   58.833333333333336,
   59.458333333333336,
   54.07407407407408,
   58.96,
   67.62962962962963,
   66.10714285714286,
   66.48,
   62.30434782608695,
   60.88,
   57.81481481481482,
   55.28,
   61.31818181818182,
   59.35714285714285,
   61.91666666666666,
   61.81481481481482,
   59.57692307692308,
   69.81481481481481,
   71.875,
   64.81481481481481,
   59.96,
   57.96,
   59.2,
   51.11111111111112,
   51.14814814814815,
   47.285714285714285,
   44.0,
   47.875,
   54.14814814814815,
   49.85714285714285,
   49.24,
   48.458333333333336,
   49.18518518518518,
   47.73076923076923,
   50.40909090909091,
   49.48148148148148,
   54.96153846153846,
   51.42307692307692,
   54.56,
   56.19230769230769,
   59.37037037037037,
   58.77777777777778,
   62.77777777777778,
   71.04347826086956,
   66.8076923076923,
   58.73076923076923,
   65.9090909090909,
   59.76,
   58.2962962962963,
   66.57692307692308,
   63.851851851851855,
   51.31818181818182,
   52.26923076923077,
   49.7037037037037,
   50.14814814814815,
   54.04,
   58.03846153846154,
   55.81481481481482,
   60.73076923076923,
   55.72,
   53.23076923076923,
   51.73076923076923,
   53.61538461538461,
   60.66666666666666,
   59.9,
   60.46153846153846,
   50.1578947368421,
   51.43478260869565,
   51.47368421052632,
   30.55,
   32.64705882352941,
   33.63636363636363,
   37.31818181818182,
   53.72222222222222,
   80.08695652173913,
   84.0,
   75.875,
   52.16666666666666,
   55.25,
   56.59090909090909,
   69.92307692307692,
   74.35,
   73.3,
   68.125,
   82.83333333333333,
   69.58333333333333,
   63.86363636363637,
   62.35,
   58.61111111111112,
   56.625,
   63.27777777777778,
   63.388888888888886,
   64.54166666666667,
   56.095238095238095,
   48.53333333333333,
   54.3,
   57.85714285714285,
   74.7,
   78.63636363636364,
   94.3,
   74.85714285714286,
   67.55,
   68.04347826086956,
   87.85714285714286,
   89.66666666666667,
   87.0],
  [1.0571428571428572,
   2.0875,
   5.112500000000001,
   0.0,
   0.6166666666666667,
   2.3125,
   0.0,
   7.887500000000001,
   8.471428571428572,
   2.775,
   1.625,
   6.03125,
   5.08,
   4.300000000000001,
   10.775,
   11.239999999999998,
   2.1066666666666665,
   1.4800000000000002,
   4.65,
   6.193333333333333,
   7.887499999999998,
   3.586666666666667,
   3.2500000000000004,
   6.624999999999999,
   4.58,
   2.5500000000000003,
   4.025,
   5.028571428571429,
   2.54375,
   1.2,
   7.762500000000001,
   7.269230769230768,
   8.893333333333333,
   7.622222222222222,
   6.941666666666666,
   2.1666666666666665,
   3.7,
   2.7875,
   5.9,
   5.846153846153848,
   2.1,
   6.03125,
   0.7466666666666666,
   5.806666666666668,
   8.071428571428571,
   5.94,
   5.435714285714285,
   3.7071428571428577,
   5.186666666666667,
   4.146153846153847,
   11.11875,
   17.137500000000003,
   15.20714285714286,
   9.785714285714286,
   2.4437500000000005,
   5.3375,
   2.48,
   3.333333333333334,
   3.712500000000001,
   3.712500000000001,
   1.7,
   1.7333333333333334,
   4.292307692307692,
   6.14375,
   11.0,
   5.21875,
   5.171428571428572,
   6.742857142857142,
   9.375,
   7.981249999999999,
   6.546666666666667,
   9.4875,
   6.84375,
   6.275,
   8.646666666666667,
   10.88125,
   6.84375,
   6.7125,
   3.578571428571429,
   2.8466666666666667,
   12.2625,
   22.1,
   10.641666666666667,
   3.2133333333333334,
   3.3687500000000004,
   9.393333333333334,
   9.156249999999996,
   6.546666666666667,
   7.293749999999999,
   7.021428571428571,
   4.333333333333333,
   12.035714285714285,
   5.4625,
   2.55,
   8.0,
   9.26875,
   3.475,
   10.85,
   4.686666666666667,
   12.61875,
   5.225,
   16.04,
   19.380000000000003,
   18.64375,
   10.425,
   9.8375,
   11.1125,
   9.386666666666663,
   7.175,
   4.566666666666666,
   14.01875,
   15.75,
   8.35,
   19.65384615384616,
   10.1875,
   6.949999999999999,
   3.83125,
   4.981249999999999,
   11.823076923076922,
   9.123076923076924,
   5.2125,
   8.575,
   9.513333333333334,
   6.49375,
   10.464285714285715,
   11.246666666666666,
   8.225,
   4.65,
   7.293333333333332,
   18.425,
   10.55625,
   7.774999999999999,
   5.1,
   8.07058823529412,
   4.16875,
   4.75,
   9.019999999999998,
   9.6125,
   8.45,
   9.3875,
   8.413333333333334,
   10.873333333333331,
   6.553333333333333,
   14.95,
   8.494736842105263,
   10.160869565217393,
   15.17692307692308,
   15.31818181818182,
   14.405555555555551,
   11.68125,
   9.4875,
   7.4071428571428575,
   9.133333333333336,
   11.93125,
   2.7812500000000004,
   3.2066666666666666,
   8.5,
   11.0,
   21.30625,
   8.485714285714284,
   9.26,
   10.08125,
   8.812500000000002,
   9.1625,
   12.85,
   11.859999999999998,
   10.513333333333332,
   11.39285714285714,
   7.425,
   10.857142857142858,
   9.387499999999998,
   7.643750000000001,
   8.91875,
   7.418750000000001,
   5.875000000000001,
   7.762499999999999,
   9.664285714285713,
   7.660000000000001,
   7.993749999999999,
   5.435714285714285,
   8.449999999999998,
   6.793333333333333,
   8.35,
   5.231250000000001,
   1.96875,
   3.481250000000001,
   5.3375,
   8.878571428571428,
   5.91875,
   5.433333333333335,
   6.73125,
   4.7,
   8.046666666666665,
   5.5625,
   6.806666666666667,
   5.21875,
   7.271428571428571,
   4.371428571428571,
   6.6000000000000005,
   7.653333333333333,
   13.656249999999998,
   12.9625,
   11.48,
   8.687500000000002,
   7.768750000000001,
   2.43125,
   2.9125000000000005,
   6.485714285714287,
   4.293750000000001,
   5.186666666666667,
   2.43125,
   1.86,
   4.7,
   5.9125000000000005,
   6.375,
   5.45,
   7.927777777777779,
   4.319999999999999,
   6.926666666666667,
   7.852941176470587,
   9.440909090909091,
   9.55,
   10.159259259259262,
   7.82142857142857,
   3.848148148148149,
   3.2296296296296303,
   6.369999999999998,
   12.725,
   14.66666666666667,
   6.325,
   1.7222222222222223,
   1.917857142857143,
   10.366666666666667,
   10.022222222222224,
   8.237037037037037,
   6.084,
   8.419230769230769,
   6.276923076923075,
   4.392592592592593,
   7.15,
   7.2719999999999985,
   5.825,
   8.903846153846153,
   6.729629629629631,
   4.148,
   13.204347826086956,
   13.263157894736842,
   11.12307692307692,
   13.961538461538463,
   13.437499999999998,
   9.1,
   10.808333333333332,
   11.52222222222222,
   11.969230769230771,
   8.15,
   10.85,
   8.526666666666666,
   4.235714285714287,
   11.9,
   3.5200000000000005,
   2.707692307692308,
   17.908333333333335,
   2.0875,
   2.56923076923077,
   6.0920000000000005,
   8.107407407407404,
   3.571428571428573,
   5.496153846153845,
   3.1478260869565218,
   2.986956521739131,
   1.7807692307692309,
   2.5200000000000005,
   3.963636363636364,
   2.582142857142858,
   3.170833333333334,
   4.122222222222223,
   3.992592592592593,
   5.770370370370371,
   3.325,
   3.2333333333333325,
   15.825,
   8.76153846153846,
   3.184000000000001,
   4.807407407407408,
   8.922222222222224,
   11.371428571428568,
   13.022222222222224,
   8.934782608695652,
   6.662962962962963,
   7.014285714285715,
   7.1160000000000005,
   7.668181818181818,
   6.459259259259259,
   9.124,
   10.695454545454549,
   13.323076923076924,
   11.546153846153846,
   11.188461538461535,
   12.388461538461542,
   5.699999999999998,
   6.044444444444444,
   7.277777777777777,
   1.7148148148148148,
   2.0130434782608697,
   1.6423076923076925,
   2.7153846153846155,
   1.4318181818181817,
   2.2320000000000007,
   4.122222222222222,
   5.784615384615384,
   2.411111111111111,
   8.172727272727274,
   12.750000000000002,
   7.074074074074074,
   3.225925925925927,
   2.968,
   2.7846153846153854,
   4.4,
   1.4961538461538462,
   4.087999999999999,
   7.138461538461537,
   11.55,
   7.7799999999999985,
   2.8400000000000003,
   2.5050000000000003,
   2.7153846153846155,
   7.999999999999998,
   6.604347826086956,
   8.289473684210526,
   15.085000000000004,
   14.494117647058824,
   12.45909090909091,
   9.185714285714289,
   1.238888888888889,
   4.269565217391306,
   2.704166666666667,
   4.945833333333334,
   5.866666666666666,
   5.666666666666666,
   4.9523809523809526,
   2.5038461538461543,
   0.925,
   1.765,
   1.3125,
   5.355555555555556,
   4.716666666666667,
   3.2818181818181817,
   3.4300000000000006,
   8.027777777777775,
   9.879166666666666,
   3.9166666666666674,
   6.731578947368422,
   6.420833333333331,
   10.414285714285716,
   15.926666666666671,
   19.40476190476191,
   6.1809523809523785,
   1.205,
   5.236363636363636,
   9.085,
   8.784210526315787,
   8.335,
   3.547826086956522,
   6.0,
   6.266666666666667,
   7.325]],
 'x': ['2016-01-01 00:00:00',
  '2016-01-02 00:00:00',
  '2016-01-03 00:00:00',
  '2016-01-04 00:00:00',
  '2016-01-05 00:00:00',
  '2016-01-06 00:00:00',
  '2016-01-07 00:00:00',
  '2016-01-08 00:00:00',
  '2016-01-09 00:00:00',
  '2016-01-10 00:00:00',
  '2016-01-11 00:00:00',
  '2016-01-12 00:00:00',
  '2016-01-13 00:00:00',
  '2016-01-14 00:00:00',
  '2016-01-15 00:00:00',
  '2016-01-16 00:00:00',
  '2016-01-17 00:00:00',
  '2016-01-18 00:00:00',
  '2016-01-19 00:00:00',
  '2016-01-20 00:00:00',
  '2016-01-21 00:00:00',
  '2016-01-22 00:00:00',
  '2016-01-23 00:00:00',
  '2016-01-24 00:00:00',
  '2016-01-25 00:00:00',
  '2016-01-26 00:00:00',
  '2016-01-27 00:00:00',
  '2016-01-28 00:00:00',
  '2016-01-29 00:00:00',
  '2016-01-30 00:00:00',
  '2016-01-31 00:00:00',
  '2016-02-01 00:00:00',
  '2016-02-02 00:00:00',
  '2016-02-03 00:00:00',
  '2016-02-04 00:00:00',
  '2016-02-05 00:00:00',
  '2016-02-06 00:00:00',
  '2016-02-07 00:00:00',
  '2016-02-08 00:00:00',
  '2016-02-09 00:00:00',
  '2016-02-10 00:00:00',
  '2016-02-11 00:00:00',
  '2016-02-12 00:00:00',
  '2016-02-13 00:00:00',
  '2016-02-14 00:00:00',
  '2016-02-15 00:00:00',
  '2016-02-16 00:00:00',
  '2016-02-17 00:00:00',
  '2016-02-18 00:00:00',
  '2016-02-19 00:00:00',

# Properties

In [63]:
from tsa.properties import *

In [64]:
trend = Trend(df, 'meantemp', 'date')

In [65]:
params = trend.plot(remove_time = True)

In [66]:
params.keys()

dict_keys(['title', 'data', 'x'])

In [67]:
outfile(params['data'])

In [68]:
trend.detrend()

             Original    Detrend
date
2016-01-01  14.714286  14.714286
2016-01-02  14.000000  13.886996
2016-01-03  14.375000  14.148993
2016-01-04  15.750000  15.410989
2016-01-05  15.833333  15.381319
...               ...        ...
2016-12-27  16.850000 -23.944323
2016-12-28  17.217391 -23.689935
2016-12-29  15.238095 -25.782235
2016-12-30  14.095238 -27.038096
2016-12-31  15.052632 -26.193706

[366 rows x 2 columns]

In [69]:
p = trend.plot_detrend(remove_time = True)

In [70]:
p.keys()

dict_keys(['title', 'data', 'data_detrend', 'x'])

In [71]:
outfile(p['x'])

## Seasonality

In [72]:
seasonality = Seasonality(df, 'humidity', 'date')

In [73]:
seasonality.seasonal()

date
2016-01-01    0.982402
2016-01-02    1.014692
2016-01-03    1.019373
2016-01-04    0.997942
2016-01-05    0.998094
                ...
2016-12-27    0.998094
2016-12-28    0.996319
2016-12-29    0.991178
2016-12-30    0.982402
2016-12-31    1.014692
Name: seasonal, Length: 366, dtype: float64

In [74]:
seasonality.deseasonalize()

             Original  Deseasonalized
date
2016-01-01  72.285714       73.580614
2016-01-02  75.875000       74.776388
2016-01-03  74.750000       73.329381
2016-01-04  77.125000       77.284053
2016-01-05  88.833333       89.002994
...               ...             ...
2016-12-27  67.550000       67.679012
2016-12-28  68.043478       68.294855
2016-12-29  87.857143       88.639088
2016-12-30  89.666667       91.272923
2016-12-31  87.000000       85.740306

[366 rows x 2 columns]

## Stationarity: now integrated with ARIMA

## Autocorrelation

In [75]:
a = Autocorrelation()

In [76]:
a.autocorrelation(df['wind_speed'])

{'title': 'Autocorrelation plot of wind_speed, order = 1',
 'y': [1.0,
  -0.21773628747133172,
  -0.23044721138987304,
  -0.052994466629175604,
  -0.022388074267325586,
  0.014921846937461658,
  0.05312516063456115,
  0.004758526414177769,
  -0.011526534450821899,
  -0.05777336996956489,
  0.012963122564644177,
  0.013673474298734249,
  0.04305626136847059,
  -0.03889861250560502,
  0.0069988857689190845,
  -0.09506613830883737,
  0.09141063867393624,
  -0.04949589795886188,
  0.0003085937441929628,
  0.10287651911324461,
  -0.01101982803560947,
  -0.08128138430563057,
  0.031158574417094954,
  -0.015546162392368475,
  -0.008745471912351107,
  0.04335055574598941],
 'x': [0,
  1,
  2,
  3,
  4,
  5,
  6,
  7,
  8,
  9,
  10,
  11,
  12,
  13,
  14,
  15,
  16,
  17,
  18,
  19,
  20,
  21,
  22,
  23,
  24,
  25],
 'upper': [0.0,
  0.10258920369235,
  0.10734273570169288,
  0.11242906256405996,
  0.11269165299970584,
  0.11273845397181459,
  0.11275923831827722,
  0.11302235312938663,
  0.1130244616598999,
  0.11303683265425446,
  0.11334717637938284,
  0.1133627784405915,
  0.11338013474859238,
  0.11355208775773043,
  0.11369224271957376,
  0.11369677713842596,
  0.11453030063941587,
  0.11529559381549362,
  0.11551900682101936,
  0.11551901549711019,
  0.11647925834717426,
  0.11649023029924083,
  0.11708560118404669,
  0.11717283667892874,
  0.11719454281639176,
  0.11720141112342418],
 'lower': [0.0,
  -0.10258920369234997,
  -0.10734273570169287,
  -0.11242906256405995,
  -0.11269165299970585,
  -0.11273845397181458,
  -0.11275923831827722,
  -0.11302235312938663,
  -0.1130244616598999,
  -0.11303683265425446,
  -0.11334717637938284,
  -0.1133627784405915,
  -0.11338013474859238,
  -0.1135520877577304,
  -0.11369224271957373,
  -0.11369677713842596,
  -0.11453030063941588,
  -0.11529559381549359,
  -0.11551900682101936,
  -0.11551901549711019,
  -0.11647925834717426,
  -0.11649023029924084,
  -0.11708560118404669,
  -0.11717283667892875,
  -0.11719454281639176,
  -0.11720141112342417]}

In [77]:
a.durbin_watson_test(df['wind_speed'], summary = True)

As value of statistic is close to 2, series is not autocorrelated.

1.0093013717263788

## Partial Autocorrelation

In [78]:
p = PartialAutocorrelation()
p.partial_autocorrelation(df['wind_speed'])

{'title': 'Partial Autocorrelation plot of wind_speed, order = 1',
 'y': [1.0,
  -0.21833446408526397,
  -0.29337184912217074,
  -0.2101654443557219,
  -0.20270792078073469,
  -0.15720413180356665,
  -0.08245513861245325,
  -0.06663509740993537,
  -0.04710820965510822,
  -0.10168814212491481,
  -0.06310557332903778,
  -0.06519524451151185,
  -0.005470940355239237,
  -0.060321227128085624,
  -0.01728325173752128,
  -0.15314985645457052,
  -0.006224463402835117,
  -0.1402571471740083,
  -0.10419807795558154,
  0.016487830450814877,
  -0.0013488067155060025,
  -0.053949213745210625,
  0.000815046189855322,
  -0.040113773199044675,
  -0.060666421140596144,
  5.136765993679539e-05],
 'x': [0,
  1,
  2,
  3,
  4,
  5,
  6,
  7,
  8,
  9,
  10,
  11,
  12,
  13,
  14,
  15,
  16,
  17,
  18,
  19,
  20,
  21,
  22,
  23,
  24,
  25],
 'upper': [0.0,
  0.10258920369235,
  0.10258920369235,
  0.10258920369235,
  0.10258920369235,
  0.10258920369235,
  0.10258920369235,
  0.10258920369235,
  0.10258920369235,
  0.10258920369235,
  0.10258920369235,
  0.10258920369235,
  0.10258920369235,
  0.10258920369235,
  0.10258920369235,
  0.10258920369235,
  0.10258920369235,
  0.10258920369235,
  0.10258920369235,
  0.10258920369235,
  0.10258920369235,
  0.10258920369235,
  0.10258920369235,
  0.10258920369235,
  0.10258920369235,
  0.10258920369235],
 'lower': [0.0,
  -0.10258920369234997,
  -0.10258920369235003,
  -0.10258920369235,
  -0.10258920369234997,
  -0.10258920369235,
  -0.10258920369235001,
  -0.10258920369235,
  -0.10258920369235,
  -0.10258920369235,
  -0.10258920369235001,
  -0.10258920369235,
  -0.10258920369235,
  -0.10258920369235,
  -0.10258920369235,
  -0.10258920369234997,
  -0.10258920369235,
  -0.10258920369235,
  -0.10258920369234999,
  -0.10258920369235,
  -0.10258920369235,
  -0.10258920369235001,
  -0.10258920369235,
  -0.10258920369234999,
  -0.10258920369235,
  -0.10258920369235]}

## Differencing: now integrated with ARIMA

# Models

## ARIMA

In [79]:
from tsa.models import Arima

In [80]:
train_df = df[:int(0.8 * len(df))]
test_df = df[int(0.8 * len(df)):]

df = train_df

In [82]:
model = Arima()
model(df, 'date', 'wind_speed')

In [83]:
model.test_stationarity()

1. ADF :  -10.516461703120978
2. P-Value :  9.934830147320276e-19
3. Num Of Lags :  0
4. Num Of Observations Used For ADF Regression and Critical Values Calculation : 291
5. Critical Values :
	 1% :  -3.4530232710482367
	 5% :  -2.871523926671883
	 10% :  -2.5720897694878424


As p-value is inside the confidence interval of 95%, series is stationary.

In [84]:
params = model.acf_plot(0)

In [85]:
params.keys()

dict_keys(['title', 'y', 'x', 'upper', 'lower'])

In [91]:
outfile(params['title'])

In [92]:
params = model.pacf_plot(0)

In [97]:
outfile(params['lower'])

In [114]:
model.fit()

                               SARIMAX Results
==============================================================================
Dep. Variable:                      y   No. Observations:                  292
Model:               SARIMAX(0, 1, 2)   Log Likelihood                -776.176
Date:                Tue, 04 Jul 2023   AIC                           1560.353
Time:                        13:04:40   BIC                           1575.046
Sample:                    01-01-2016   HQIC                          1566.239
                         - 10-18-2016
Covariance Type:                  opg
==============================================================================
                 coef    std err          z      P>|z|      [0.025      0.975]
------------------------------------------------------------------------------
intercept      0.0117      0.022      0.521      0.602      -0.032       0.056
ma.L1         -0.5683      0.044    -12.965      0.000      -0.654      -0.482
ma.L2         -0.3406      0.046     -7.473      0.000      -0.430      -0.251
sigma2        12.0752      0.871     13.866      0.000      10.368      13.782
===================================================================================
Ljung-Box (L1) (Q):                   0.02   Jarque-Bera (JB):                53.58
Prob(Q):                              0.88   Prob(JB):                         0.00
Heteroskedasticity (H):               1.08   Skew:                             0.79
Prob(H) (two-sided):                  0.71   Kurtosis:                         4.39
===================================================================================

Warnings:
[1] Covariance matrix calculated using the outer product of gradients (complex-step).

In [115]:
model.error_metrics(test_df, 'wind_speed')

  Metric      Value
0   MAPE   1.149710
1    MAE   3.548570
2    MSE  17.858804

In [116]:
params = model.plot_forecast(test_df, 'wind_speed', exclude_time=True)

In [118]:
outfile(params['y_forecast'])